name: Automated Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black==24.4.2 codespell

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Spell check docs and markdown
        run: |
          codespell --ignore-words-list=nd,ist --skip .git,*.png,*.jpg,*.zip

      - name: Validate markdown structure (agents)
        run: |
          missing=0
          for f in *.md; do
            [ -f "$f" ] || continue
            if ! grep -q "^# " "$f"; then echo "::warning file=$f::Top-level heading missing"; fi
            if ! grep -q "^## Role" "$f"; then echo "::warning file=$f::Missing '## Role' section"; fi
            if ! grep -q "^## Core Expertise" "$f"; then echo "::warning file=$f::Missing '## Core Expertise' section"; fi
          done

      - name: Report success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '✅ Automated review checks passed (Black, codespell, markdown validation).'
            })

      - name: Report failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Automated review checks failed. Please address formatting/spelling/structure issues.'
            })

